[[Alldata]]
[[Alldata.data]]
pos = {x = 4.5,y = 0.0}

[[Alldata.data]]
pos = {x = 7.0, y = -1.5}

[[Alldata.data]]
pos = {x = 7.0, y = -5}

[[Alldata]]
[[Alldata.data]]
pos = {x = -4.5,y = 0.0}

[[Alldata.data]]
pos = {x = -7.0, y = -1.5}

[[Alldata.data]]
pos = {x = -7.0, y = -5}


[[Alldata]]
[[Alldata.data]]
pos = {x = -2.0, y = 6}

[[Alldata.data]]
pos = {x = -2.0,y = 4}

[[Alldata.data]]
pos = {x = -8.5, y = -1}

[[Alldata.data]]
pos = {x = -8.5, y = -5}


[[Alldata]]
[[Alldata.data]]
pos = {x = 2.0, y = 6}
[[Alldata.data]]
pos = {x = 2.0,y = 4}

[[Alldata.data]]
pos = {x = 8.5, y = -1}

[[Alldata.data]]
pos = {x = 8.5, y = -5}

[[Alldata]]
[[Alldata.data]]
pos = {x = -7.0, y = -7}

[[Alldata.data]]
pos = {x = -7.0, y = -8.5}

[[Alldata.data]]
pos = {x = -10.5, y = -11.5}

[[Alldata]]
[[Alldata.data]]
pos = {x = 7.0, y = -7}

[[Alldata.data]]
pos = {x = 7.0, y = -8.5}

[[Alldata.data]]
pos = {x = 10.5, y = -11.5}

[[Alldata]]
[[Alldata.data]]
pos = {x = 16.0, y = -25}
[[Alldata.data]]
pos = {x = 16.0,y = 3}
[[Alldata.data]]
pos = {x = 14.0,y = 3}
[[Alldata.data]]
pos = {x = 14.0,y = -25}

[[round_data]]
pos = {x = 0,y = -17.8}
r = 12.2
angle = 1.0

[[round_data]]
pos = {x = 0,y = -17.8}
r = 12.2
angle = 1

[[round_data]]
pos = {x = -6.5,y = -5.0}
r = 2.0
angle = 8

[[round_data]]
pos = {x = 6.5,y = -5.0}
r = 2.0
angle = 8

[[round_data]]
pos = {x = 0,y = -18.0}
r = 10.4
angle = 0.85

[[round_data]]
pos = {x = 7.5,y = -21.2}
r = 2.1
angle = 15

[[round_data]]
pos = {x = -7.5,y = -21.2}
r = 2.2
angle = 15

[[round_data]]
pos = {x = 10.3,y = -25.0}
r = 5.7
angle = 10

[[round_data]]
pos = {x = 10.2,y = -25.0}
r = 3.8
angle = 10

[[range]]
pos = {x = -121.2,y = 29.2}

[[range]]
pos = {x = 38.5,y = 121.2}
[[range]]
pos = {x = -11,y = -2}

[[range]]
pos = {x = 2,y = 11}

[[range]]
pos = {x = -88,y = 88}

[[range]]
pos = {x = -3,y = 10}

[[range]]
pos = {x = -10,y = 3}

[[range]]
pos = {x = -5.1,y = 9}

[[range]]
pos = {x = -4.0,y = 9.6}

[[triangle]]
pos = {x1 = -5.5, y1 = -5, x2 = -5.5, y2 = -2.5, x3 = -3, y3 = -1.0}

[[triangle]]
pos = {x1 = 5.5, y1 = -5, x2 = 5.5, y2 = -2.5, x3 = 3, y3 = -1.0}

[[roundbumper]]
pos = {x = 6.5,y = -24.5}

[[roundbumper]]
pos = {x = -6.5,y=-24.5}

[straightbumper]
pos = {x = -2.0,y = 5.5}
size = {w = 4,h = 0.7}

[spinnerdata]
pos = {x = 6.65,y = -28.55}
adjust = {x = -0.84,y = 0.0}
size = {x = 2.0,y = 0.1}

[[ItemRect]]
pos = {x =0.0,y = -29.5}
size = {w = 1,h = 0.5}

[[ItemRect]]
pos = {x = 3.8,y = -18.5}
size = {w = 1,h = 0.5}

[[ItemRect]]
pos = {x = -5.8,y = -12.5}
size = {w = 1,h = 0.5}


[[enemydata]]
pos = {x = -9.2, y = -23}
size = {w = 4,h = 4}
error = {x = -1.3, y = -1.2}
angle = 120

[[enemydata]]
pos = {x = 5.8, y = -22.5}
size = {w = 3.5,h = 3.5}
error = {x = -0.2, y = -1.3}
angle = 40



